@real @virtual_network

Feature: Virtual network

  Scenario: Creting a resource group
    Given I have no messages on the buffer
    And I request "azure_resource_group.create.azure" with "rg_create.json"
    When I request "azure_virtual_network.create.azure" with "vn_create.json"
    Then I should get a "azure_virtual_network.create.azure.done" response with "name" as "vn_test"
    And I should get a "azure_virtual_network.create.azure.done" response with "address_space.0" as "10.0.0.0/16"
    And I should get a "azure_virtual_network.create.azure.done" response with "dns_server_names.0" as "10.0.0.4"
    And I should get a "azure_virtual_network.create.azure.done" response with "dns_server_names.1" as "10.0.0.5"
    And I should get a "azure_virtual_network.create.azure.done" response with "subnets.0.name" as "sub_test"
    And I should get a "azure_virtual_network.create.azure.done" response with "subnets.0.address_prefix" as "10.0.1.0/24"
    And I should get a "azure_virtual_network.create.azure.done" response with "location" as "westus"
    And I should get a "azure_virtual_network.create.azure.done" response with "tags.t1" as "one"
    And I should get a "azure_virtual_network.create.azure.done" response with "tags.t2" as "two"
    When I request "azure_virtual_network.update.azure" with "vn_update.json"
    Then I should get a "azure_virtual_network.update.azure.done" response with "name" as "vn_test"
    And I should get a "azure_virtual_network.update.azure.done" response with "address_space.0" as "10.0.0.0/16"
    And I should get a "azure_virtual_network.update.azure.done" response with "address_space.1" as "10.1.3.0/24"
    And I should get a "azure_virtual_network.update.azure.done" response with "dns_server_names.0" as "10.0.0.4"
    And I should get a "azure_virtual_network.update.azure.done" response with "dns_server_names.1" as "10.0.0.5"
    And I should get a "azure_virtual_network.update.azure.done" response with "subnets.0.name" as "sub_test"
    And I should get a "azure_virtual_network.update.azure.done" response with "subnets.0.address_prefix" as "10.0.1.0/24"
    And I should get a "azure_virtual_network.update.azure.done" response with "location" as "westus"
    And I should get a "azure_virtual_network.update.azure.done" response with "tags.t1" as "one"
    And I should get a "azure_virtual_network.update.azure.done" response with "tags.t2" as "two"
    And I should get a "azure_virtual_network.update.azure.done" response with "tags.t3" as "three"
    When I request "azure_virtual_network.get.azure" with "vn_update.json"
    Then I should get a "azure_virtual_network.get.azure.done" response with "name" as "vn_test"
    And I should get a "azure_virtual_network.get.azure.done" response with "address_space.0" as "10.0.0.0/16"
    And I should get a "azure_virtual_network.get.azure.done" response with "address_space.1" as "10.1.3.0/24"
    And I should get a "azure_virtual_network.get.azure.done" response with "dns_server_names.0" as "10.0.0.4"
    And I should get a "azure_virtual_network.get.azure.done" response with "dns_server_names.1" as "10.0.0.5"
    And I should get a "azure_virtual_network.get.azure.done" response with "subnets.0.name" as "sub_test"
    And I should get a "azure_virtual_network.get.azure.done" response with "subnets.0.address_prefix" as "10.0.1.0/24"
    And I should get a "azure_virtual_network.get.azure.done" response with "location" as "westus"
    And I should get a "azure_virtual_network.get.azure.done" response with "tags.t1" as "one"
    When I request "azure_virtual_network.delete.azure" with "vn_update.json"
    Then I should get a "azure_virtual_network.delete.azure.done" response with "name" as "vn_test"
    And I should get a "azure_virtual_network.delete.azure.done" response with "address_space.0" as "10.0.0.0/16"
    And I should get a "azure_virtual_network.delete.azure.done" response with "dns_server_names.0" as "10.0.0.4"
    And I should get a "azure_virtual_network.delete.azure.done" response with "dns_server_names.1" as "10.0.0.5"
    And I should get a "azure_virtual_network.delete.azure.done" response with "subnets.0.name" as "sub_test"
    And I should get a "azure_virtual_network.delete.azure.done" response with "subnets.0.address_prefix" as "10.0.1.0/24"
    And I should get a "azure_virtual_network.delete.azure.done" response with "location" as "westus"
    And I should get a "azure_virtual_network.delete.azure.done" response with "tags.t1" as "one"
    And I should get a "azure_virtual_network.delete.azure.done" response with "tags.t2" as "two"
    And I request "azure_virtual_network.get.azure" with "vn_update.json"
    Then I should get a "azure_virtual_network.get.azure.error" response with "error" containing "Resource group 'rg_test' could not be found."
